spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: HZ
        namespace: d83c21cc-2614-41ea-ad2b-17a4ef3d596f
  application:
    name: user-service
server:
  port: 10091
